import os
import sys
import json
import argparse
import re
import requests
import tempfile
from wechat_api import WeChatClient

def process_content_images(client, html_content, base_dir):
    """
    Finds all <img> tags, uploads local/remote images to WeChat CDN, 
    and replaces the src attributes.
    """
    # Pattern to find src in <img> tags
    img_pattern = r'<img([^>]*?)src=["\']([^"\']+)["\']([^>]*?)>'
    
    def replacer(match):
        prefix = match.group(1)
        src = match.group(2)
        suffix = match.group(3)
        
        # Skip if already a WeChat URL
        if "mmbiz.qpic.cn" in src:
            return match.group(0)
            
        temp_file = None
        try:
            if src.startswith(('http://', 'https://')):
                # External URL: Download to temp file
                print(f"  → Downloading remote image: {src[:50]}...")
                response = requests.get(src, timeout=10)
                if response.status_code == 200:
                    ext = os.path.splitext(src.split('?')[0])[1] or '.jpg'
                    fd, temp_path = tempfile.mkstemp(suffix=ext)
                    with os.fdopen(fd, 'wb') as tmp:
                        tmp.write(response.content)
                    temp_file = temp_path
                    upload_path = temp_path
                else:
                    print(f"  ⚠ Failed to download image: {src}")
                    return match.group(0)
            else:
                # Local path
                # Try relative to the HTML content file or base_dir
                upload_path = os.path.join(base_dir, src.lstrip('/'))
                if not os.path.exists(upload_path):
                    # Try direct path
                    upload_path = src
                    
                if not os.path.exists(upload_path):
                    print(f"  ⚠ Local image not found: {src}")
                    return match.group(0)

            # Upload to WeChat CDN
            print(f"  → Uploading to WeChat CDN: {os.path.basename(upload_path)}...")
            wechat_url = client.upload_content_image(upload_path)
            print(f"  ✅ Uploaded. URL: {wechat_url[:50]}...")
            
            return f'<img{prefix}src="{wechat_url}"{suffix}>'
            
        except Exception as e:
            print(f"  ⚠ Error processing image {src}: {e}")
            return match.group(0)
        finally:
            if temp_file and os.path.exists(temp_file):
                os.remove(temp_file)

    return re.sub(img_pattern, replacer, html_content)

def load_config():
    """Load config from a standard location or local directory."""
    config_paths = [
        'config.json',
        os.path.join(os.path.dirname(__file__), 'config.json'),
        os.path.expanduser('~/.wechat_config.json')
    ]
    for path in config_paths:
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                return json.load(f)
    return {}

def main():
    parser = argparse.ArgumentParser(description="Universal WeChat Official Account Draft Publisher")
    parser.add_argument("-t", "--title", help="Article title (auto-detected if missing)")
    parser.add_argument("-c", "--content", required=True, help="Path to the HTML content file")
    parser.add_argument("--cover", help="Path to the cover image file (auto-detected if missing)")
    parser.add_argument("-a", "--author", help="Article author (auto-detected if missing, default: 弹壳呱呱)")
    parser.add_argument("--appid", help="WeChat AppID (overrides config)")
    parser.add_argument("--secret", help="WeChat AppSecret (overrides config)")

    args = parser.parse_args()

    # Try to load metadata from sibling JSON file (generated by md_to_wechat.py)
    metadata = {}
    meta_path = os.path.splitext(args.content)[0] + ".json"
    if os.path.exists(meta_path):
        try:
            with open(meta_path, 'r', encoding='utf-8') as f:
                metadata = json.load(f)
            print(f"✅ Loaded metadata from {meta_path}")
        except Exception as e:
            print(f"⚠ Warning: Failed to load metadata file: {e}")

    # Resolve Article Info (Arg > Metadata > Default)
    title = args.title or metadata.get('title')
    author = args.author or metadata.get('author') or "弹壳呱呱"
    cover_path = args.cover or metadata.get('image')
    
    # Handle relative image path in frontmatter
    if cover_path and not os.path.isabs(cover_path) and not os.path.exists(cover_path):
        # Try relative to the content file
        potential_path = os.path.join(os.path.dirname(args.content), cover_path.lstrip('/'))
        if os.path.exists(potential_path):
            cover_path = potential_path

    if not title:
        print("❌ Error: Article title is required. Provide via --title or Frontmatter.")
        sys.exit(1)
        
    if not cover_path:
        print("❌ Error: Cover image is required. Provide via --cover or Frontmatter.")
        sys.exit(1)

    # Resolve credentials
    config = load_config()
    appid = args.appid or config.get('appid')
    appsecret = args.secret or config.get('appsecret')

    if not appid or not appsecret:
        print("❌ Error: AppID or AppSecret missing. Provide via --appid/--secret or a config.json file.")
        sys.exit(1)

    if not os.path.exists(args.content):
        print(f"❌ Error: Content file not found: {args.content}")
        sys.exit(1)

    if not os.path.exists(cover_path):
        print(f"❌ Error: Cover image not found: {cover_path}")
        sys.exit(1)

    client = WeChatClient(appid, appsecret)

    try:
        # 1. Upload Cover
        print(f"→ Uploading cover: {os.path.basename(cover_path)}...")
        thumb_media_id = client.upload_image(cover_path, is_thumb=True)
        print(f"✅ Cover uploaded. MediaID: {thumb_media_id}")

        # 2. Read Content
        with open(args.content, 'r', encoding='utf-8') as f:
            html_content = f.read()
            
        # 3. Process and Upload content images
        print("→ Processing content images...")
        html_content = process_content_images(client, html_content, os.path.dirname(os.path.abspath(args.content)))

        # 4. Create Draft
        print(f"→ Creating draft: '{title}'...")
        draft_media_id = client.create_draft(
            title=title,
            html_content=html_content,
            thumb_media_id=thumb_media_id,
            author=author
        )
        
        print("\n" + "="*40)
        print("🚀 PUBLISH SUCCESSFUL!")
        print(f"Draft MediaID: {draft_media_id}")
        print("="*40)
        print("您现在可以前往微信公众号后台“草稿箱”查看。")

    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
